changes made for swymed
PSMRI/TM-API pull request #14
Opened 2023-08-18 10:14 UTC by Vidyaaa24

2023-08-23 10:23 UTC, harimohanr commented on src/main/java/com/iemr/tm/controller/videoconsultation/VideoConsultationController.java
> +	public String CallVideoConsultationAndJitsi(@PathVariable("fromuserID") Long fromuserID,
@Vidyaaa24 Method name starts with capital letter. please correct it

2023-08-23 10:24 UTC, harimohanr commented on src/main/java/com/iemr/tm/controller/videoconsultation/VideoConsultationController.java
> +	public String CallVanVideoConsultationAndJitsi(@PathVariable("fromuserID") Long fromuserID,
@Vidyaaa24 Method name starts with capital letter

2023-08-23 10:26 UTC, harimohanr requested changes
@Vidyaaa24 Fix the review comments and resubmit

2023-08-24 10:01 UTC, Anjana2310 commented on src/main/java/com/iemr/tm/controller/videoconsultation/VideoConsultationController.java
> +package com.iemr.tm.controller.videoconsultation;
controller word is missing

2023-08-24 10:45 UTC, Anjana2310 commented on src/main/java/com/iemr/tm/service/videoconsultation/VideoConsultationServiceImpl.java
> +	private String videoConsultationDNSName = ConfigProperties.getPropertyByName("videoConsultationDNSName");
ConfigProperties.getPropertyByName("swymed_dnsname");
swymed_dnsname is a property mentioned in application.properties.

2023-08-24 10:47 UTC, Anjana2310 commented on src/main/java/com/iemr/tm/controller/videoconsultationcontroller/VideoConsultationController.java
> +			if (Type.equalsIgnoreCase("VideoConsultation")) {
if (Type.equalsIgnoreCase("Swymed"))

2023-08-24 10:56 UTC, Anjana2310 commented on src/main/java/com/iemr/tm/controller/videoconsultationcontroller/VideoConsultationController.java
> +	public String callVanVideoConsultationAndJitsi(@PathVariable("fromuserID") Long fromuserID,
We will maintain the previous name

2023-08-24 10:57 UTC, Anjana2310 requested changes
@Vidyaaa24 Pls fix the review comments

2023-08-24 12:59 UTC, harimohanr approved these changes
@looks oka to me

2023-08-24 12:59 UTC, merged